version: '3'
services:
  client:
    image: shehinshaji/react-app:latest
    container_name: client
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/build
    pull_policy: always
    ports:
      - "8080:80"

